# Generated by Django 5.2.16 on 2026-07-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='business_name',
        ),
    ]
