# Generated by Django 5.2.16 on 2026-07-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_citizen_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='address',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='phone_number',
        ),
    ]
