# Generated by Django 5.2.16 on 2026-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_citizen_address_remove_citizen_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CARNE_DE_EXTRANJERIA', 'Carné de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('INSPECTOR', 'Inspector'), ('FUNCIONARIO', 'Funcionario')], max_length=20),
        ),
    ]
