# Generated by Django 5.2.16 on 2026-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('business_category', models.CharField(choices=[('RESTAURANT', 'Restaurante'), ('COMERCIO', 'Comercio'), ('ALMACEN', 'Almacén'), ('SERVICIOS', 'Servicios'), ('INDUSTRIA', 'Industria')], max_length=20)),
                ('square_meters', models.PositiveIntegerField()),
            ],
        ),
    ]
