# Generated by Django 5.2.16 on 2026-07-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='citizens',
            field=models.ManyToManyField(related_name='companies', to='users.citizen'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='organizations.company'),
        ),
    ]
