# Generated by Django 5.2.16 on 2026-07-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CARNET_EXTRANJERIA', 'Carné de extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
