# Generated by Django 5.2.16 on 2026-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('procedure_type', models.CharField(choices=[('LICENCIA_DE_FUNCIONAMIENTO', 'Licencia de Funcionamiento'), ('ITSE', 'ITSE')], max_length=50)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_DE_REVISION', 'Pendiente de revisión'), ('DOCUMENTOS_APROBADOS', 'Documentos aprobados'), ('PENDIENTE_DE_INSPECCION', 'Pendiente de inspección'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=50)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
    ]
