# Generated by Django 5.2.16 on 2026-07-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('allowed_formats', models.JSONField(default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('procedure_type', models.CharField(choices=[('LICENCIA_DE_FUNCIONAMIENTO', 'Licencia de Funcionamiento'), ('ITSE', 'ITSE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('procedure_type', models.CharField(choices=[('LICENCIA_DE_FUNCIONAMIENTO', 'Licencia de Funcionamiento'), ('ITSE', 'ITSE')], max_length=50)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_DE_REVISION', 'Pendiente de revisión'), ('DOCUMENTOS_APROBADOS', 'Documentos aprobados'), ('PENDIENTE_DE_INSPECCION', 'Pendiente de inspección'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to='users.citizen')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to='organizations.establishment')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='ProcedureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_requirements', to='procedures.casefile')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.requirement')),
            ],
            options={
                'verbose_name': 'Requisito del expediente',
                'verbose_name_plural': 'Requisitos del expediente',
            },
        ),
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('validation_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procedure_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procedures.procedurerequirement')),
            ],
            options={
                'verbose_name': 'Documento adjunto',
                'verbose_name_plural': 'Documentos adjuntos',
            },
        ),
    ]
