# Generated by Django 5.2.16 on 2026-07-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('procedures', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to='users.employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to='users.employee'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to='users.citizen'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to='organizations.establishment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='case_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='procedures.casefile'),
        ),
        migrations.AddField(
            model_name='procedurerequirement',
            name='case_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_requirements', to='procedures.casefile'),
        ),
        migrations.AddField(
            model_name='attacheddocument',
            name='procedure_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procedures.procedurerequirement'),
        ),
        migrations.AddField(
            model_name='procedurerequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.requirement'),
        ),
        migrations.AddConstraint(
            model_name='procedurerequirement',
            constraint=models.UniqueConstraint(fields=('case_file', 'requirement'), name='unique_case_file_requirement'),
        ),
    ]
