# Generated by Django 5.2.16 on 2026-07-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacheddocument',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
