# Generated by Django 5.2.16 on 2026-07-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('allowed_file_type', models.CharField(default='pdf,jpg,jpeg,png', max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('applies_to', models.CharField(blank=True, choices=[('LICENCIA_FUNCIONAMIENTO', 'Licencia de funcionamiento'), ('ITSE', 'ITSE')], max_length=50, null=True)),
            ],
        ),
    ]
