# Generated by Django 5.2.16 on 2026-07-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('citizens', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('LICENCIA_FUNCIONAMIENTO', 'Licencia de funcionamiento'), ('ITSE', 'ITSE')], max_length=50)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=20)),
                ('tracking_code', models.CharField(max_length=50, unique=True)),
                ('business_type', models.CharField(max_length=255)),
                ('premises_size', models.IntegerField()),
                ('premises_address', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('DOCUMENTOS_APROBADOS', 'Documentos aprobados'), ('PENDIENTE_INSPECCION', 'Pendiente de inspección'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.attachment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement')),
            ],
            options={
                'unique_together': {('record', 'requirement')},
            },
        ),
    ]
