# Generated by Django 5.2.16 on 2026-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No aprobado')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
            },
        ),
    ]
