# Generated by Django 5.2.16 on 2026-07-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='procedures.casefile'),
        ),
    ]
